-- ─────────────────────────────────────────────────────────────────────────────
-- Creatorverse database setup
--
-- Run this in your Supabase project: Dashboard → SQL Editor → New query → paste
-- → Run. It creates the `creators` table and seeds 5 starter creators so your
-- homepage isn't empty.
--
-- The prework also asks you to: uncheck "Enable Row Level Security" and check
-- "Enable Realtime" when creating the table via the Table editor UI. This script
-- creates the table directly and leaves RLS disabled (the default when created
-- via SQL), which is what the prework wants for this exercise.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz default now(),
  name        text not null,
  url         text not null,
  description text,
  "imageURL"  text
);

-- Optional: enable Realtime so changes broadcast live
alter publication supabase_realtime add table creators;

-- Seed data: 5 starter creators
insert into creators (name, url, description, "imageURL") values
  (
    'Fireship',
    'https://www.youtube.com/@Fireship',
    'High-intensity, fast-paced "code report" videos and 100-second explainers covering web dev, new frameworks, and tech news.',
    'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=600&q=80'
  ),
  (
    'Theo - t3.gg',
    'https://www.youtube.com/@t3dotgg',
    'Opinionated takes on modern full-stack TypeScript, React, and the ever-changing JavaScript ecosystem.',
    'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=600&q=80'
  ),
  (
    'Web Dev Simplified',
    'https://www.youtube.com/@WebDevSimplified',
    'Clear, beginner-friendly tutorials that break down JavaScript, React, and CSS concepts into digestible lessons.',
    'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&q=80'
  ),
  (
    'The Coding Train',
    'https://www.youtube.com/@TheCodingTrain',
    'Creative coding with Daniel Shiffman — p5.js, generative art, and playful, enthusiastic programming challenges.',
    'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80'
  ),
  (
    'Kevin Powell',
    'https://www.youtube.com/@KevinPowell',
    'The "CSS evangelist" — deep, practical lessons that make modern CSS and responsive layouts click.',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80'
  );
